### ISSUE TITLE
[Issue] 1.20.1 JAMD Crash on dim load

### ISSUE THREAD

**Issue by Zelioth** [nanite/JAMD#21] opened 2023-10-08 18:23 UTC
### Minecraft Version

1.20.1

### Modloader

47.2.1

### Mod version

3.3.3

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

https://gist.github.com/Zelioth/c038ee95b9db27482559d7f827000d05

### Steps to reproduce the issue

1. Install JAMD
2. Go to JAMD
3. Crash 

### Description of the issue you are having

I couldn't include the log. This is happening on the server environment and there is no way I could find in the log where this happened. It happened when someone visited the JAMD. It does seem to happen every time. 

If you have any questions Our mod pack is Friends United 2.0 
https://www.curseforge.com/minecraft/modpacks/friends-united-2-0

### Information

- [X] I have provided as much information as possible

**Comment by lubitzd** [comment] 2023-10-19 23:42
I'm having a similar issue and have isolated the issue to the Aethersteel mod. Unsure if this is caused by the same mod as your issue. I'm also using the same versions of MC, Forge, and JAMD.
I have also written an issue on Aethersteel's Github [here](https://github.com/Ross2750/Aethersteel/issues/3) as I am not sure which mod is responsible.
[crash-2023-10-19_18.04.43-server.txt](https://github.com/nanite/JAMD/files/13048472/crash-2023-10-19_18.04.43-server.txt)

**Comment by UnRealDinnerbone** [comment] 2023-10-19 23:42
You need to blacklist Aethersteel (I working a rewrite that should be out in the next day for two that will fix the issue)

**Comment by lubitzd** [comment] 2023-10-19 23:44
Thanks for the quick response! How would I go about doing that?

**Comment by UnRealDinnerbone** [comment] 2023-10-19 23:45
config/jamd.json

added aethersteel:.*   to the blacklist

**Comment by lubitzd** [comment] 2023-10-19 23:49
Rad, that works. Thanks again; I can close the issue on the Aethersteel Github then.

**Comment by Zelioth** [comment] 2023-10-20 02:30
wait, I don't have a mod named AetherSteel. I have the Aether mod. could that be the issue? Adding that line above to the config causes a crash on startup for me

**Comment by UnRealDinnerbone** [comment] 2023-10-31 13:37
A bit busy this week, I try and get the updated version out next week

**Comment by Auvrae** [comment] 2023-11-03 21:21
> wait, I don't have a mod named AetherSteel. I have the Aether mod. could that be the issue? Adding that line above to the config causes a crash on startup for me

In a JSON Array you need to have a comma after each item so it would look like this
`"item",
"item2",
"aethersteel:.*"`

In my case it was supreme_mining_dimension:.* that was causing the issue for me. You should just remove everything and slowly add mods until it breaks, to figure out which mod is causing the issue.

The last item doesn't need a comma.
Hope that helps until UnReal finishes the update!

**Comment by UnRealDinnerbone** [comment] 2023-11-07 18:04
All Crashes should be fixed in 3.4.0
Configs have moved to jamd/dimtype.json and should load in 'most' mods ores by default. If a mod does not get loaded in by default, you can add it your self and or open an issue, so I can add mod support.

**Closed as completed by UnRealDinnerbone** 2023-11-07 18:04 UTC
